spring:
  application:
    name: dubbo-consumer

server:
  port: 5002

dubbo:
  application:
    name: caicai-dubbo-comsumer
  scan:
    base-packages: com.caicai.dubboInterface
  #  和服务提供者配置的差异主要在于这里不用配置 protocol 暴露端口号了，因为消费者不会占用一个端口。
  #  但在实际开发中，一个业务应用往往既是服务提供者又是服务消费者，所以往往都需要配置 protocol。
  protocol:
    port: 20881
    name: dubbo

  #  dubbo.registry.address 、dubbo.config-center.address 和 dubbo.metadata-report.address：
  #  dubbo 注册中心、配置中心、元数据中心的配置地址，同时指向 Nacos。
  registry:
#    address: nacos://localhost:8848
    address: zookeeper://localhost:2181
    simplified: true
  config-center:
#    address: nacos://localhost:8848
    address: zookeeper://localhost:2181
  metadata-report:
#    address: nacos://localhost:8848
    address: zookeeper://localhost:2181
